// Auto-generated by scripts/build-graph.ts — do not edit by hand
// Generated: 2026-04-11T06:05:29.853Z
// Nodes: 118 | Edges: 228

export type NodeType =
  | "process"
  | "polarity"
  | "voltage"
  | "material"
  | "gas"
  | "duty_cycle"
  | "defect"
  | "problem"
  | "setup_phase"
  | "image";

export type EdgeType =
  | "uses_polarity"
  | "supports_voltage"
  | "welds_material"
  | "requires_gas"
  | "has_duty_cycle"
  | "has_setup_phase"
  | "has_problem"
  | "depicted_in"
  | "causes"
  | "fixed_by"
  | "applies_to"
  | "related_to";

export interface GraphNode {
  id: string;
  type: NodeType;
  label: string;
  meta?: Record<string, unknown>;
}

export interface GraphEdge {
  source: string;
  target: string;
  type: EdgeType;
  label?: string;
  meta?: Record<string, unknown>;
}

export const nodes: GraphNode[] = [
  {
    "id": "process:mig",
    "type": "process",
    "label": "MIG",
    "meta": {
      "full_name": "MIG / Solid Core Gas Shielded Welding",
      "polarity_type": "DCEP",
      "skill_level": "Low to Moderate",
      "thickness_range": "22 Gauge to 3/8\""
    }
  },
  {
    "id": "process:flux_cored",
    "type": "process",
    "label": "Flux-Cored",
    "meta": {
      "full_name": "Flux-Cored / Self-Shielded Gasless Welding",
      "polarity_type": "DCEN",
      "skill_level": "Low",
      "thickness_range": "18 Gauge to 5/16\""
    }
  },
  {
    "id": "process:tig",
    "type": "process",
    "label": "TIG",
    "meta": {
      "full_name": "TIG / GTAW (Gas Tungsten Arc Welding)",
      "polarity_type": "DCEN",
      "skill_level": "High",
      "thickness_range": "24 Gauge to 3/16\""
    }
  },
  {
    "id": "process:stick",
    "type": "process",
    "label": "Stick",
    "meta": {
      "full_name": "Stick / SMAW (Shielded Metal Arc Welding)",
      "polarity_type": "DCEP",
      "skill_level": "Moderate to High",
      "thickness_range": "10 Gauge to 1/2\""
    }
  },
  {
    "id": "polarity:dcep",
    "type": "polarity",
    "label": "DCEP",
    "meta": {
      "full_name": "Direct Current Electrode Positive"
    }
  },
  {
    "id": "polarity:dcen",
    "type": "polarity",
    "label": "DCEN",
    "meta": {
      "full_name": "Direct Current Electrode Negative"
    }
  },
  {
    "id": "voltage:120vac",
    "type": "voltage",
    "label": "120VAC"
  },
  {
    "id": "voltage:240vac",
    "type": "voltage",
    "label": "240VAC"
  },
  {
    "id": "material:mild_steel",
    "type": "material",
    "label": "Mild Steel"
  },
  {
    "id": "material:stainless_steel",
    "type": "material",
    "label": "Stainless Steel"
  },
  {
    "id": "material:aluminum_with_optional_spool_gun",
    "type": "material",
    "label": "Aluminum (with optional Spool Gun)"
  },
  {
    "id": "material:chrome_moly",
    "type": "material",
    "label": "Chrome Moly"
  },
  {
    "id": "material:steel",
    "type": "material",
    "label": "Steel"
  },
  {
    "id": "material:aluminum",
    "type": "material",
    "label": "Aluminum"
  },
  {
    "id": "material:castings",
    "type": "material",
    "label": "Castings"
  },
  {
    "id": "material:magnesium_alloys",
    "type": "material",
    "label": "Magnesium alloys"
  },
  {
    "id": "gas:c25",
    "type": "gas",
    "label": "C25 (75% Ar / 25% CO2)",
    "meta": {
      "description": "For mild steel MIG"
    }
  },
  {
    "id": "gas:stainless_tri_mix",
    "type": "gas",
    "label": "Stainless Tri-Mix",
    "meta": {
      "description": "For stainless MIG"
    }
  },
  {
    "id": "gas:100pct_argon",
    "type": "gas",
    "label": "100% Argon",
    "meta": {
      "description": "For TIG and aluminum MIG"
    }
  },
  {
    "id": "gas:none",
    "type": "gas",
    "label": "No Gas Required",
    "meta": {
      "description": "Self-shielded or flux-coated"
    }
  },
  {
    "id": "duty_cycle:mig_120vac_100a",
    "type": "duty_cycle",
    "label": "MIG 120VAC 40%@100A",
    "meta": {
      "process": "MIG",
      "voltage": "120VAC",
      "amperage": 100,
      "duty_cycle_percent": 40,
      "weld_minutes": 4,
      "rest_minutes": 6
    }
  },
  {
    "id": "duty_cycle:mig_120vac_75a",
    "type": "duty_cycle",
    "label": "MIG 120VAC 100%@75A",
    "meta": {
      "process": "MIG",
      "voltage": "120VAC",
      "amperage": 75,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "duty_cycle:mig_240vac_200a",
    "type": "duty_cycle",
    "label": "MIG 240VAC 25%@200A",
    "meta": {
      "process": "MIG",
      "voltage": "240VAC",
      "amperage": 200,
      "duty_cycle_percent": 25,
      "weld_minutes": 2.5,
      "rest_minutes": 7.5
    }
  },
  {
    "id": "duty_cycle:mig_240vac_115a",
    "type": "duty_cycle",
    "label": "MIG 240VAC 100%@115A",
    "meta": {
      "process": "MIG",
      "voltage": "240VAC",
      "amperage": 115,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "duty_cycle:tig_120vac_125a",
    "type": "duty_cycle",
    "label": "TIG 120VAC 40%@125A",
    "meta": {
      "process": "TIG",
      "voltage": "120VAC",
      "amperage": 125,
      "duty_cycle_percent": 40,
      "weld_minutes": 4,
      "rest_minutes": 6
    }
  },
  {
    "id": "duty_cycle:tig_120vac_90a",
    "type": "duty_cycle",
    "label": "TIG 120VAC 100%@90A",
    "meta": {
      "process": "TIG",
      "voltage": "120VAC",
      "amperage": 90,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "duty_cycle:tig_240vac_175a",
    "type": "duty_cycle",
    "label": "TIG 240VAC 30%@175A",
    "meta": {
      "process": "TIG",
      "voltage": "240VAC",
      "amperage": 175,
      "duty_cycle_percent": 30,
      "weld_minutes": 3,
      "rest_minutes": 7
    }
  },
  {
    "id": "duty_cycle:tig_240vac_105a",
    "type": "duty_cycle",
    "label": "TIG 240VAC 100%@105A",
    "meta": {
      "process": "TIG",
      "voltage": "240VAC",
      "amperage": 105,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "duty_cycle:stick_120vac_80a",
    "type": "duty_cycle",
    "label": "Stick 120VAC 40%@80A",
    "meta": {
      "process": "Stick",
      "voltage": "120VAC",
      "amperage": 80,
      "duty_cycle_percent": 40,
      "weld_minutes": 4,
      "rest_minutes": 6
    }
  },
  {
    "id": "duty_cycle:stick_120vac_60a",
    "type": "duty_cycle",
    "label": "Stick 120VAC 100%@60A",
    "meta": {
      "process": "Stick",
      "voltage": "120VAC",
      "amperage": 60,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "duty_cycle:stick_240vac_175a",
    "type": "duty_cycle",
    "label": "Stick 240VAC 25%@175A",
    "meta": {
      "process": "Stick",
      "voltage": "240VAC",
      "amperage": 175,
      "duty_cycle_percent": 25,
      "weld_minutes": 2.5,
      "rest_minutes": 7.5
    }
  },
  {
    "id": "duty_cycle:stick_240vac_100a",
    "type": "duty_cycle",
    "label": "Stick 240VAC 100%@100A",
    "meta": {
      "process": "Stick",
      "voltage": "240VAC",
      "amperage": 100,
      "duty_cycle_percent": 100,
      "weld_minutes": 10,
      "rest_minutes": 0
    }
  },
  {
    "id": "defect:wire_spatter",
    "type": "defect",
    "label": "spatter (wire)",
    "meta": {
      "process_group": "wire",
      "causes": [
        "Voltage too high",
        "Wrong polarity",
        "CTWD too long",
        "Contaminated base metal"
      ],
      "corrections": [
        "Decrease voltage",
        "Check polarity",
        "Reduce CTWD",
        "Clean base metal"
      ]
    }
  },
  {
    "id": "defect:wire_poor_penetration",
    "type": "defect",
    "label": "poor penetration (wire)",
    "meta": {
      "process_group": "wire",
      "causes": [
        "Voltage too low",
        "Travel speed too fast",
        "Current too low"
      ],
      "corrections": [
        "Increase voltage",
        "Decrease travel speed",
        "Increase current"
      ]
    }
  },
  {
    "id": "defect:wire_burn_through",
    "type": "defect",
    "label": "burn through (wire)",
    "meta": {
      "process_group": "wire",
      "causes": [
        "Current too high",
        "Travel speed too slow",
        "Gap too large"
      ],
      "corrections": [
        "Decrease current",
        "Increase travel speed",
        "Reduce gap"
      ]
    }
  },
  {
    "id": "defect:wire_example_good_weld",
    "type": "defect",
    "label": "Wire: Good Weld",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Proper voltage",
        "Correct wire feed speed",
        "Appropriate travel speed",
        "Optimal CTWD"
      ],
      "corrections": [
        "Maintain current parameters"
      ]
    }
  },
  {
    "id": "defect:wire_example_voltage_too_low_or_wire_feed_too_slow",
    "type": "defect",
    "label": "Wire: Voltage Too Low or Wire Feed Too Slow",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Insufficient voltage",
        "Wire feed speed too slow"
      ],
      "corrections": [
        "Increase Output Voltage",
        "Increase Wire Feed Speed"
      ]
    }
  },
  {
    "id": "defect:wire_example_voltage_too_high_or_wire_feed_too_fast",
    "type": "defect",
    "label": "Wire: Voltage Too High or Wire Feed Too Fast",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Excessive voltage",
        "Wire feed speed too fast"
      ],
      "corrections": [
        "Decrease Output Voltage",
        "Decrease Wire Feed Speed"
      ]
    }
  },
  {
    "id": "defect:wire_example_travel_speed_too_fast",
    "type": "defect",
    "label": "Wire: Travel Speed Too Fast",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Gun moving too quickly"
      ],
      "corrections": [
        "Reduce travel speed"
      ]
    }
  },
  {
    "id": "defect:wire_example_travel_speed_too_slow",
    "type": "defect",
    "label": "Wire: Travel Speed Too Slow",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Gun moving too slowly"
      ],
      "corrections": [
        "Increase travel speed"
      ]
    }
  },
  {
    "id": "defect:wire_example_ctwd_too_long_or_wrong_polarity",
    "type": "defect",
    "label": "Wire: CTWD Too Long or Wrong Polarity",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Contact tip too far from work",
        "Incorrect polarity setting"
      ],
      "corrections": [
        "Check Polarity and maintain less than 1/2 inch CTWD"
      ]
    }
  },
  {
    "id": "defect:stick_slag",
    "type": "defect",
    "label": "slag (stick)",
    "meta": {
      "process_group": "stick",
      "causes": [
        "Improper cleaning",
        "Poor technique",
        "Contaminated electrode"
      ],
      "corrections": [
        "Clean welds first before inspection",
        "Improve welding technique",
        "Use fresh electrodes"
      ]
    }
  },
  {
    "id": "defect:stick_undercut",
    "type": "defect",
    "label": "undercut (stick)",
    "meta": {
      "process_group": "stick",
      "causes": [
        "Current too high",
        "Arc length too long",
        "Travel speed too fast"
      ],
      "corrections": [
        "Decrease current",
        "Shorten arc length",
        "Reduce travel speed"
      ]
    }
  },
  {
    "id": "defect:stick_poor_penetration",
    "type": "defect",
    "label": "poor penetration (stick)",
    "meta": {
      "process_group": "stick",
      "causes": [
        "Current too low",
        "Travel speed too fast"
      ],
      "corrections": [
        "Increase current",
        "Decrease travel speed"
      ]
    }
  },
  {
    "id": "defect:stick_burn_through",
    "type": "defect",
    "label": "burn through (stick)",
    "meta": {
      "process_group": "stick",
      "causes": [
        "Current too high",
        "Travel speed too slow",
        "Arc length too short"
      ],
      "corrections": [
        "Decrease current",
        "Increase travel speed",
        "Maintain proper arc length"
      ]
    }
  },
  {
    "id": "defect:stick_example_good_weld",
    "type": "defect",
    "label": "Stick: Good Weld",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Proper current setting",
        "Correct travel speed",
        "Appropriate arc length"
      ],
      "corrections": [
        "Maintain current parameters"
      ]
    }
  },
  {
    "id": "defect:stick_example_current_too_low",
    "type": "defect",
    "label": "Stick: Current Too Low",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Insufficient amperage"
      ],
      "corrections": [
        "Increase the current"
      ]
    }
  },
  {
    "id": "defect:stick_example_current_too_high",
    "type": "defect",
    "label": "Stick: Current Too High",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Excessive amperage"
      ],
      "corrections": [
        "Decrease the current"
      ]
    }
  },
  {
    "id": "defect:stick_example_weld_speed_too_fast",
    "type": "defect",
    "label": "Stick: Weld Speed Too Fast",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Electrode moving too quickly"
      ],
      "corrections": [
        "Weld slower"
      ]
    }
  },
  {
    "id": "defect:stick_example_weld_speed_too_slow",
    "type": "defect",
    "label": "Stick: Weld Speed Too Slow",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Electrode moving too slowly"
      ],
      "corrections": [
        "Weld faster"
      ]
    }
  },
  {
    "id": "defect:stick_example_arc_length_too_short",
    "type": "defect",
    "label": "Stick: Arc Length Too Short",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Electrode held too close to work piece"
      ],
      "corrections": [
        "Increase distance"
      ]
    }
  },
  {
    "id": "defect:stick_example_arc_length_too_long",
    "type": "defect",
    "label": "Stick: Arc Length Too Long",
    "meta": {
      "role": "example_weld",
      "causes": [
        "Electrode held too far from work piece"
      ],
      "corrections": [
        "Decrease distance"
      ]
    }
  },
  {
    "id": "problem:wire_feed_motor_runs_but_wire_does_not_feed_proper",
    "type": "problem",
    "label": "Wire Feed Motor Runs but Wire Does Not Feed Properly",
    "meta": {
      "causes": [
        "Insufficient wire feed pressure",
        "Incorrect wire feed roller size",
        "Damaged MIG Gun, cable, or liner assembly",
        "Feed Tensioner is too tight"
      ],
      "solutions": [
        "Increase wire feed pressure properly. Follow step 27 on page 17.",
        "Flip roll to correct size. Follow the Feed Roller instructions on page 12.",
        "Have a qualified technician inspect these parts and replace as necessary.",
        "Loosen Feed Tensioner so it applies only enough pressure to prevent continued spinning after the Gun Trigger is released."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:wire_creates_a_bird_s_nest_during_operation",
    "type": "problem",
    "label": "Wire Creates a Bird's Nest During Operation",
    "meta": {
      "causes": [
        "Excess wire feed pressure",
        "Incorrect Contact Tip size",
        "MIG Gun Cable Connector not fully inserted into Wire Feed mechanism",
        "Damaged liner"
      ],
      "solutions": [
        "Adjust wire feed pressure properly. Follow step 27 on page 17.",
        "Replace with the proper tip for wire used.",
        "Insert Gun Cable Connector properly. Follow steps 13 and 14 on page 13.",
        "Have a qualified technician inspect and repair or replace as necessary."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:wire_stops_during_welding",
    "type": "problem",
    "label": "Wire Stops During Welding",
    "meta": {
      "causes": [
        "Gun cable is severely bent and Wire Feed mechanism cannot feed wire",
        "Gun liner is clogged or worn",
        "Gun liner is too small for welding wire being used",
        "Wire is tangled on the spool",
        "Wire is not making contact with Feed Rollers",
        "Feed Roller is not making enough contact with wire or is crushing flux-cored wire"
      ],
      "solutions": [
        "Straighten Gun cable.",
        "Check gun liner for obstruction. Replace if necessary.",
        "Check that gun liner is correct size for wire.",
        "Check wire for cross winding or tangled spool.",
        "Check Feed Rollers and ensure correct groove for wire diameter is being used.",
        "Check Feed Tensioner and ensure it is set properly."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:welding_arc_not_stable",
    "type": "problem",
    "label": "Welding Arc Not Stable",
    "meta": {
      "causes": [
        "Wire not feeding properly",
        "Incorrect Contact Tip or liner size or excessive wear",
        "Incorrect wire feed speed",
        "Loose MIG Gun cable or ground cable",
        "Damaged MIG Gun or loose connection within Gun",
        "Incorrect polarity for process being run",
        "Gas coverage may be insufficient or too high",
        "Poor connection with workpiece"
      ],
      "solutions": [
        "See first Troubleshooting section above.",
        "Replace with the proper tip or liner size for wire used.",
        "Adjust wire feed speed to achieve a more stable arc.",
        "Check to ensure that all connections are tight.",
        "Have a qualified technician inspect and repair/replace as necessary.",
        "Ensure polarity is correct for operation: DCEP for MIG welding and DCEN for Flux-Cored self-shielded welding.",
        "Ensure gas flow rate is set according to Settings Chart. Make sure MIG Gun Cable Connector is fully inserted into Wire Feed mechanism with no O-Rings exposed.",
        "Check the ground clamp connection to the workpiece and machine. Ensure the MIG Gun is properly secured."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:weak_arc_strength",
    "type": "problem",
    "label": "Weak Arc Strength",
    "meta": {
      "causes": [
        "Incorrect line voltage",
        "Improper gauge or length of cord",
        "Not enough current"
      ],
      "solutions": [
        "Check the line voltage and, if insufficient, have a licensed electrician remedy the situation.",
        "Do not use an extension cord on this Welder. Use only one of the supplied power cords for this Welder or an identical replacement cord.",
        "Switch current to proper setting for metal thickness."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:welder_does_not_function_when_switched_on",
    "type": "problem",
    "label": "Welder Does Not Function When Switched On",
    "meta": {
      "causes": [
        "Tripped thermal protection device",
        "Circuit supplies insufficient input voltage or amperage",
        "Faulty or improperly connected Trigger",
        "Machine is in low- or over-voltage protection",
        "Machine is in the incorrect mode"
      ],
      "solutions": [
        "If a warning screen appears in the LCD Display window, Welder may have overheated and shut down. Stop and wait with the Power Switch ON for the Welder to cool. Reduce duration or frequency of welding periods.",
        "Verify that the circuit is designed to supply the required input voltage and amperage as detailed on the Specifications table. Check input voltage to ensure it is within specified range.",
        "Ensure the gun connection is properly seated on machine. Qualified technician must check and secure/replace Trigger.",
        "Check input voltage and ensure it falls within the specified range. If input voltage is correct, press Reset Button on back of machine.",
        "Ensure the correct process has been selected."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored",
        "TIG",
        "Stick"
      ]
    }
  },
  {
    "id": "problem:lcd_display_does_not_light_when_welder_is_switched",
    "type": "problem",
    "label": "LCD Display Does Not Light When Welder is Switched On",
    "meta": {
      "causes": [
        "Unit is not connected to outlet properly",
        "Outlet is unpowered",
        "Plug does not have correct rating",
        "Circuit breaker has tripped due to high input amperage",
        "Input Power Cord is not seated properly"
      ],
      "solutions": [
        "Verify the voltage at the outlet and the connection to the outlet.",
        "Check circuit breaker/GFCI devices; if any are tripped, determine and remedy cause before resetting.",
        "Make sure installed plug is correct rating. See Specifications on page 7.",
        "Press Reset Button on back of machine to reset circuit breaker.",
        "Ensure the twist lock input Power Cord is fully secured."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored",
        "TIG",
        "Stick"
      ]
    }
  },
  {
    "id": "problem:wire_feeds_but_arc_does_not_ignite",
    "type": "problem",
    "label": "Wire Feeds, but Arc Does Not Ignite",
    "meta": {
      "causes": [
        "Improper ground connection",
        "Improperly sized Contact Tip",
        "Excessively worn Contact Tip",
        "Dirty Contact Tip"
      ],
      "solutions": [
        "Make certain that the workpiece is contacted properly by the Ground Clamp and that the workpiece is properly cleaned near the ground clamp and welding location.",
        "Verify that Contact Tip is the proper size for welding wire. If needed, replace Contact Tip with proper size and type.",
        "Check that the hole in the tip is not deformed or enlarged. If needed, replace Contact Tip with proper size and type.",
        "Properly clean Contact Tip."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:porosity_in_the_weld_metal",
    "type": "problem",
    "label": "Porosity in the Weld Metal",
    "meta": {
      "causes": [
        "Shielding gas bottle is empty",
        "Not enough or too much shielding gas",
        "Dirty workpiece",
        "Gun is being used too far away from workpiece",
        "Polarity is incorrect for the application",
        "Dirty welding wire is introducing contamination into the weld"
      ],
      "solutions": [
        "Check gas bottle and replenish as necessary.",
        "Check gas regulator to ensure proper flow.",
        "Clean workpiece down to bare metal.",
        "Check CTWD (contact tip to work distance) for the proper procedure.",
        "Check the polarity and ensure it is DCEP for MIG and DCEN for Flux-Cored.",
        "Make certain that welding wire is clean and free of rust and residues."
      ],
      "applicable_processes": [
        "MIG",
        "Flux-Cored"
      ]
    }
  },
  {
    "id": "problem:welder_does_not_function_when_switched_on_tig_stic",
    "type": "problem",
    "label": "Welder Does Not Function When Switched On (TIG/Stick)",
    "meta": {
      "causes": [
        "Tripped thermal protection device",
        "Faulty or improperly connected Trigger",
        "Ground Clamp not attached to workpiece",
        "Shielding Gas not connected"
      ],
      "solutions": [
        "Reduce duration or frequency of welding periods to help reduce wear on the welder. Refer to Duty Cycle (Duration of Use) on page 29.",
        "Qualified technician must check and secure/replace Trigger.",
        "Attach Ground Clamp to workpiece.",
        "Connect shielding gas to Welder."
      ],
      "applicable_processes": [
        "TIG",
        "Stick"
      ]
    }
  },
  {
    "id": "problem:weak_arc_strength_tig_stick",
    "type": "problem",
    "label": "Weak Arc Strength (TIG/Stick)",
    "meta": {
      "causes": [
        "Incorrect line voltage",
        "Improper gauge or length of cord"
      ],
      "solutions": [
        "Check the line voltage and, if insufficient, have a licensed electrician remedy the situation.",
        "Do not use an extension cord on this Welder. Use only one of the supplied power cords for this Welder or an identical replacement cord."
      ],
      "applicable_processes": [
        "TIG",
        "Stick"
      ]
    }
  },
  {
    "id": "problem:welding_arc_not_stable_tig_stick",
    "type": "problem",
    "label": "Welding Arc Not Stable (TIG/Stick)",
    "meta": {
      "causes": [
        "Loose electrode cable or ground cable",
        "Damaged electrode holder or loose connection within electrode holder",
        "Adjust current setting",
        "Shielding gas getting low"
      ],
      "solutions": [
        "Check to ensure that all connections are tight.",
        "Have a qualified technician inspect and repair/replace as necessary.",
        "Make sure setting matches recommended setting on chart.",
        "Replace shielding gas cylinder."
      ],
      "applicable_processes": [
        "TIG",
        "Stick"
      ]
    }
  },
  {
    "id": "setup:mig_wire_spool_installation",
    "type": "setup_phase",
    "label": "MIG: Wire Spool Installation",
    "meta": {
      "process": "MIG",
      "phase": "Wire Spool Installation",
      "step_count": 5
    }
  },
  {
    "id": "setup:mig_feed_roller_setup",
    "type": "setup_phase",
    "label": "MIG: Feed Roller Setup",
    "meta": {
      "process": "MIG",
      "phase": "Feed Roller Setup",
      "step_count": 5
    }
  },
  {
    "id": "setup:mig_gun_cable_connection",
    "type": "setup_phase",
    "label": "MIG: Gun Cable Connection",
    "meta": {
      "process": "MIG",
      "phase": "Gun Cable Connection",
      "step_count": 4
    }
  },
  {
    "id": "setup:mig_wire_feed_control_cable",
    "type": "setup_phase",
    "label": "MIG: Wire Feed Control Cable",
    "meta": {
      "process": "MIG",
      "phase": "Wire Feed Control Cable",
      "step_count": 3
    }
  },
  {
    "id": "setup:mig_polarity_setup_dcep_for_mig",
    "type": "setup_phase",
    "label": "MIG: Polarity Setup — DCEP for MIG",
    "meta": {
      "process": "MIG",
      "phase": "Polarity Setup — DCEP for MIG",
      "step_count": 2
    }
  },
  {
    "id": "setup:mig_gas_setup",
    "type": "setup_phase",
    "label": "MIG: Gas Setup",
    "meta": {
      "process": "MIG",
      "phase": "Gas Setup",
      "step_count": 5
    }
  },
  {
    "id": "setup:mig_wire_threading",
    "type": "setup_phase",
    "label": "MIG: Wire Threading",
    "meta": {
      "process": "MIG",
      "phase": "Wire Threading",
      "step_count": 8
    }
  },
  {
    "id": "setup:mig_power_up_and_wire_feed",
    "type": "setup_phase",
    "label": "MIG: Power Up and Wire Feed",
    "meta": {
      "process": "MIG",
      "phase": "Power Up and Wire Feed",
      "step_count": 6
    }
  },
  {
    "id": "setup:mig_drive_tension_test",
    "type": "setup_phase",
    "label": "MIG: Drive Tension Test",
    "meta": {
      "process": "MIG",
      "phase": "Drive Tension Test",
      "step_count": 4
    }
  },
  {
    "id": "setup:mig_final_assembly",
    "type": "setup_phase",
    "label": "MIG: Final Assembly",
    "meta": {
      "process": "MIG",
      "phase": "Final Assembly",
      "step_count": 4
    }
  },
  {
    "id": "setup:mig_lcd_settings",
    "type": "setup_phase",
    "label": "MIG: LCD Settings",
    "meta": {
      "process": "MIG",
      "phase": "LCD Settings",
      "step_count": 7
    }
  },
  {
    "id": "setup:flux_cored_differences",
    "type": "setup_phase",
    "label": "Flux-Cored: Differences from MIG",
    "meta": {
      "process": "Flux-Cored",
      "differences": [
        "Polarity: Ground Clamp → Positive (+) Socket, Wire Feed Power Cable → Negative (–) Socket",
        "Feed Roller: Use Knurled Groove side (not V-Groove)",
        "Feed Tensioner: Set to 2-3 (lower than MIG's 3-5) — flux-cored wire crushes easily",
        "No gas cylinder, regulator, or gas hose needed",
        "Use drag angle (0-15° in weld direction) instead of push angle",
        "Weld will be covered by slag — clean off with chipping hammer and wire brush"
      ]
    }
  },
  {
    "id": "setup:tig_connect_cables",
    "type": "setup_phase",
    "label": "TIG: Connect Cables",
    "meta": {
      "process": "TIG",
      "phase": "Connect Cables",
      "step_count": 3
    }
  },
  {
    "id": "setup:tig_connect_shielding_gas",
    "type": "setup_phase",
    "label": "TIG: Connect Shielding Gas",
    "meta": {
      "process": "TIG",
      "phase": "Connect Shielding Gas",
      "step_count": 4
    }
  },
  {
    "id": "setup:tig_connect_power_cord",
    "type": "setup_phase",
    "label": "TIG: Connect Power Cord",
    "meta": {
      "process": "TIG",
      "phase": "Connect Power Cord",
      "step_count": 2
    }
  },
  {
    "id": "setup:tig_sharpen_tungsten_electrode",
    "type": "setup_phase",
    "label": "TIG: Sharpen Tungsten Electrode",
    "meta": {
      "process": "TIG",
      "phase": "Sharpen Tungsten Electrode",
      "step_count": 8
    }
  },
  {
    "id": "setup:tig_assemble_tig_torch",
    "type": "setup_phase",
    "label": "TIG: Assemble TIG Torch",
    "meta": {
      "process": "TIG",
      "phase": "Assemble TIG Torch",
      "step_count": 8
    }
  },
  {
    "id": "setup:tig_lcd_settings",
    "type": "setup_phase",
    "label": "TIG: LCD Settings",
    "meta": {
      "process": "TIG",
      "phase": "LCD Settings",
      "step_count": 13
    }
  },
  {
    "id": "setup:tig_welding_technique",
    "type": "setup_phase",
    "label": "TIG: Welding Technique",
    "meta": {
      "process": "TIG",
      "phase": "Welding Technique",
      "step_count": 10
    }
  },
  {
    "id": "setup:stick_connect_cables",
    "type": "setup_phase",
    "label": "Stick: Connect Cables",
    "meta": {
      "process": "Stick",
      "phase": "Connect Cables",
      "step_count": 3
    }
  },
  {
    "id": "setup:stick_connect_power_cord",
    "type": "setup_phase",
    "label": "Stick: Connect Power Cord",
    "meta": {
      "process": "Stick",
      "phase": "Connect Power Cord",
      "step_count": 2
    }
  },
  {
    "id": "setup:stick_lcd_settings",
    "type": "setup_phase",
    "label": "Stick: LCD Settings",
    "meta": {
      "process": "Stick",
      "phase": "LCD Settings",
      "step_count": 12
    }
  },
  {
    "id": "setup:stick_welding_technique",
    "type": "setup_phase",
    "label": "Stick: Welding Technique",
    "meta": {
      "process": "Stick",
      "phase": "Welding Technique",
      "step_count": 7
    }
  },
  {
    "id": "image:front_panel_layout",
    "type": "image",
    "label": "Labeled diagram of all front panel controls: Home/Back buttons, Control/Left/Rig",
    "meta": {
      "topic": "front_panel_layout",
      "images": [
        "owner_p08_front_panel.png"
      ],
      "keywords": [
        "front panel",
        "controls",
        "knobs",
        "buttons",
        "LCD",
        "sockets",
        "where is",
        "which socket",
        "power switch",
        "home button",
        "back button"
      ]
    }
  },
  {
    "id": "image:interior_controls",
    "type": "image",
    "label": "Labeled diagram of interior: Wire Spool, Spool Knob, Wire Feed Mechanism, Wire I",
    "meta": {
      "topic": "interior_controls",
      "images": [
        "owner_p09_interior_controls.png"
      ],
      "keywords": [
        "interior",
        "inside",
        "wire feed mechanism",
        "feed tensioner",
        "idler arm",
        "wire spool",
        "spool knob",
        "feed roller",
        "foot pedal socket",
        "wire feed control socket",
        "cold wire feed switch"
      ]
    }
  },
  {
    "id": "image:polarity_mig_dcep",
    "type": "image",
    "label": "DCEP setup for MIG: Ground Clamp in Negative socket, Wire Feed Power Cable in Po",
    "meta": {
      "topic": "polarity_mig_dcep",
      "images": [
        "owner_p14_mig_polarity_dcep_gas.png",
        "qsg_p02_cable_setups.png"
      ],
      "keywords": [
        "MIG polarity",
        "DCEP",
        "solid core polarity",
        "gas shielded polarity",
        "MIG cable setup"
      ]
    }
  },
  {
    "id": "image:polarity_flux_dcen",
    "type": "image",
    "label": "DCEN setup for Flux-Cored: Ground Clamp in Positive socket, Wire Feed Power Cabl",
    "meta": {
      "topic": "polarity_flux_dcen",
      "images": [
        "owner_p13_flux_polarity_dcen.png",
        "qsg_p02_cable_setups.png"
      ],
      "keywords": [
        "flux-cored polarity",
        "DCEN",
        "gasless polarity",
        "flux cable setup"
      ]
    }
  },
  {
    "id": "image:polarity_tig",
    "type": "image",
    "label": "TIG setup: Ground Clamp in Positive, TIG Torch in Negative, Foot Pedal in Foot P",
    "meta": {
      "topic": "polarity_tig",
      "images": [
        "owner_p24_tig_cable_setup.png",
        "qsg_p02_cable_setups.png"
      ],
      "keywords": [
        "TIG polarity",
        "TIG cable",
        "TIG setup",
        "TIG torch",
        "foot pedal",
        "argon"
      ]
    }
  },
  {
    "id": "image:polarity_stick",
    "type": "image",
    "label": "Stick setup: Ground Clamp in Negative, Electrode Holder in Positive. No gas, no ",
    "meta": {
      "topic": "polarity_stick",
      "images": [
        "owner_p27_stick_cable_setup.png",
        "qsg_p02_cable_setups.png"
      ],
      "keywords": [
        "stick polarity",
        "stick cable",
        "stick setup",
        "electrode holder",
        "SMAW"
      ]
    }
  },
  {
    "id": "image:polarity_all_processes",
    "type": "image",
    "label": "Quick Start Guide page 2: side-by-side cable setup photos for all 4 processes (S",
    "meta": {
      "topic": "polarity_all_processes",
      "images": [
        "qsg_p02_cable_setups.png"
      ],
      "keywords": [
        "all polarity",
        "cable setup",
        "which cable",
        "compare processes",
        "switch process"
      ]
    }
  },
  {
    "id": "image:wire_spool_installation",
    "type": "image",
    "label": "Wire spool installation for both 1-2 lb and 10-12 lb spools with labeled diagram",
    "meta": {
      "topic": "wire_spool_installation",
      "images": [
        "owner_p10_wire_spool_1_2lb.png",
        "owner_p11_wire_spool_10_12lb.png"
      ],
      "keywords": [
        "wire spool",
        "install spool",
        "spool loading",
        "wingnut",
        "spacer",
        "spool adapter",
        "brake pad"
      ]
    }
  },
  {
    "id": "image:feed_roller_selection",
    "type": "image",
    "label": "Feed Roller types: V-Groove (solid core) vs Knurled Groove (flux-cored), with wi",
    "meta": {
      "topic": "feed_roller_selection",
      "images": [
        "owner_p12_feed_roller.png"
      ],
      "keywords": [
        "feed roller",
        "V-groove",
        "knurled",
        "roller size",
        "wire size",
        "flip roller"
      ]
    }
  },
  {
    "id": "image:wire_threading_and_tension",
    "type": "image",
    "label": "Wire threading through liner, tensioner latching, cold wire feed procedure, driv",
    "meta": {
      "topic": "wire_threading_and_tension",
      "images": [
        "owner_p15_wire_threading.png",
        "owner_p16_cold_wire_feed.png",
        "owner_p17_tension_test_nozzle_spool_gun.png"
      ],
      "keywords": [
        "wire threading",
        "wire feed",
        "tension",
        "idler arm",
        "feed tensioner",
        "cold wire feed",
        "tension test"
      ]
    }
  },
  {
    "id": "image:gun_cable_connector",
    "type": "image",
    "label": "Correct vs incorrect Gun Cable Connector insertion into Wire Feed mechanism",
    "meta": {
      "topic": "gun_cable_connector",
      "images": [
        "owner_p13_flux_polarity_dcen.png"
      ],
      "keywords": [
        "gun cable",
        "connector",
        "MIG gun",
        "not fully inserted",
        "O-ring"
      ]
    }
  },
  {
    "id": "image:gas_cylinder_setup",
    "type": "image",
    "label": "Gas cylinder mounting, valve cleaning, regulator connection, gas hose to welder",
    "meta": {
      "topic": "gas_cylinder_setup",
      "images": [
        "owner_p14_mig_polarity_dcep_gas.png",
        "owner_p25_tig_gas_setup.png"
      ],
      "keywords": [
        "gas cylinder",
        "regulator",
        "gas hose",
        "C25",
        "argon",
        "shielding gas",
        "SCFH"
      ]
    }
  },
  {
    "id": "image:duty_cycle_mig",
    "type": "image",
    "label": "MIG duty cycle visual: 120V 40%@100A (4min weld/6min rest), 100%@75A. 240V 25%@2",
    "meta": {
      "topic": "duty_cycle_mig",
      "images": [
        "owner_p19_duty_cycle_mig.png"
      ],
      "keywords": [
        "duty cycle",
        "MIG duty",
        "overheating",
        "how long can I weld",
        "rest time",
        "thermal protection"
      ]
    }
  },
  {
    "id": "image:duty_cycle_tig_stick",
    "type": "image",
    "label": "TIG and Stick duty cycles. TIG: 120V 40%@125A/100%@90A, 240V 30%@175A/100%@105A.",
    "meta": {
      "topic": "duty_cycle_tig_stick",
      "images": [
        "owner_p29_duty_cycle_tig_stick.png"
      ],
      "keywords": [
        "TIG duty cycle",
        "stick duty cycle",
        "TIG overheating",
        "stick overheating"
      ]
    }
  },
  {
    "id": "image:settings_mig",
    "type": "image",
    "label": "MIG LCD settings walkthrough: process selection, wire diameter, material thickne",
    "meta": {
      "topic": "settings_mig",
      "images": [
        "owner_p20_settings_mig.png",
        "owner_p21_optional_settings_gas.png"
      ],
      "keywords": [
        "MIG settings",
        "wire diameter",
        "material thickness",
        "wire feed speed",
        "voltage setting",
        "inductance",
        "run-in WFS",
        "spot timer",
        "synergic"
      ]
    }
  },
  {
    "id": "image:settings_tig",
    "type": "image",
    "label": "TIG LCD settings: process selection, 100% Argon, rod diameter, material thicknes",
    "meta": {
      "topic": "settings_tig",
      "images": [
        "owner_p30_settings_tig.png"
      ],
      "keywords": [
        "TIG settings",
        "rod diameter",
        "TIG amperage",
        "energize torch"
      ]
    }
  },
  {
    "id": "image:settings_stick",
    "type": "image",
    "label": "Stick LCD settings: process, electrode type (60xx/70xx), electrode diameter, mat",
    "meta": {
      "topic": "settings_stick",
      "images": [
        "owner_p32_settings_stick.png"
      ],
      "keywords": [
        "stick settings",
        "electrode type",
        "electrode diameter",
        "hot start",
        "arc force",
        "60xx",
        "70xx"
      ]
    }
  },
  {
    "id": "image:welding_technique_wire",
    "type": "image",
    "label": "Wire welding technique: stringer vs weave bead, 90° butt / 45° fillet angles, pu",
    "meta": {
      "topic": "welding_technique_wire",
      "images": [
        "owner_p22_wire_welding_technique.png"
      ],
      "keywords": [
        "stringer bead",
        "weave bead",
        "push angle",
        "drag angle",
        "CTWD",
        "contact tip to work distance",
        "gun angle",
        "fillet",
        "butt weld"
      ]
    }
  },
  {
    "id": "image:electrode_grinding_torch_assembly",
    "type": "image",
    "label": "Tungsten electrode sharpening technique and TIG torch exploded assembly view (Ba",
    "meta": {
      "topic": "electrode_grinding_torch_assembly",
      "images": [
        "owner_p26_electrode_grinding_torch_assembly.png"
      ],
      "keywords": [
        "tungsten",
        "electrode",
        "grinding",
        "sharpen",
        "TIG torch",
        "collet",
        "collet body",
        "ceramic nozzle",
        "back cap"
      ]
    }
  },
  {
    "id": "image:weld_diagnosis_wire",
    "type": "image",
    "label": "Wire weld diagnosis: cross-section penetration diagrams, 6 example weld photos (",
    "meta": {
      "topic": "weld_diagnosis_wire",
      "images": [
        "owner_p35_wire_weld_diagnosis.png",
        "owner_p36_wire_penetration_defects.png",
        "owner_p37_wire_porosity_spatter_burn.png"
      ],
      "keywords": [
        "wire weld diagnosis",
        "MIG weld quality",
        "flux weld quality",
        "penetration",
        "porosity",
        "spatter",
        "burn-through",
        "voltage too low",
        "voltage too high",
        "travel speed",
        "CTWD too long",
        "weld looks bad",
        "holes in weld",
        "lumpy weld"
      ]
    }
  },
  {
    "id": "image:weld_diagnosis_stick",
    "type": "image",
    "label": "Stick weld diagnosis: cross-section penetration, 7 example weld photos (good, cu",
    "meta": {
      "topic": "weld_diagnosis_stick",
      "images": [
        "owner_p38_stick_weld_diagnosis.png",
        "owner_p39_stick_penetration_defects.png",
        "owner_p40_stick_porosity_spatter_burn.png"
      ],
      "keywords": [
        "stick weld diagnosis",
        "stick weld quality",
        "current too low",
        "current too high",
        "arc length",
        "stick weld looks bad"
      ]
    }
  },
  {
    "id": "image:strike_test",
    "type": "image",
    "label": "Strike test procedure (hammer test: good weld bends, poor weld snaps) and weld c",
    "meta": {
      "topic": "strike_test",
      "images": [
        "owner_p34_strike_test_cleaning.png"
      ],
      "keywords": [
        "strike test",
        "test weld",
        "good weld",
        "poor weld",
        "cleaning weld",
        "chipping hammer",
        "wire brush",
        "slag"
      ]
    }
  },
  {
    "id": "image:wiring_schematic",
    "type": "image",
    "label": "Full electrical wiring schematic: AC input, rectifier bridge, PFC, IGBT inverter",
    "meta": {
      "topic": "wiring_schematic",
      "images": [
        "owner_p45_wiring_schematic.png"
      ],
      "keywords": [
        "wiring schematic",
        "electrical diagram",
        "circuit",
        "MCU board",
        "IGBT",
        "PFC",
        "transformer",
        "rectifier",
        "internal wiring"
      ]
    }
  },
  {
    "id": "image:assembly_exploded",
    "type": "image",
    "label": "Exploded isometric assembly diagram with 61 numbered callouts matching the parts",
    "meta": {
      "topic": "assembly_exploded",
      "images": [
        "owner_p47_assembly_diagram.png"
      ],
      "keywords": [
        "assembly diagram",
        "exploded view",
        "parts diagram",
        "internal parts",
        "where is part"
      ]
    }
  },
  {
    "id": "image:parts_list",
    "type": "image",
    "label": "61-item parts list table with part numbers, descriptions, and quantities",
    "meta": {
      "topic": "parts_list",
      "images": [
        "owner_p46_parts_list.png"
      ],
      "keywords": [
        "parts list",
        "part number",
        "replacement parts",
        "how many",
        "quantity"
      ]
    }
  },
  {
    "id": "image:maintenance",
    "type": "image",
    "label": "Maintenance: pre-use inspection checklist, MIG Gun Nozzle/Contact Tip cleaning (",
    "meta": {
      "topic": "maintenance",
      "images": [
        "owner_p41_maintenance.png"
      ],
      "keywords": [
        "maintenance",
        "cleaning",
        "nozzle cleaning",
        "contact tip",
        "LCD screen cover",
        "inspection"
      ]
    }
  },
  {
    "id": "image:settings_chart_door",
    "type": "image",
    "label": "Photo of the Settings Chart printed on inside of welder door — quick reference f",
    "meta": {
      "topic": "settings_chart_door",
      "images": [
        "door_panel_chart.webp"
      ],
      "keywords": [
        "settings chart",
        "door panel",
        "quick reference",
        "inside door",
        "rated duty cycles summary"
      ]
    }
  },
  {
    "id": "image:selection_chart",
    "type": "image",
    "label": "Welding process selection decision chart: skill level, gas requirements, materia",
    "meta": {
      "topic": "selection_chart",
      "images": [
        "selection_chart.png"
      ],
      "keywords": [
        "which process",
        "how to choose",
        "which welder",
        "flux vs MIG",
        "MIG vs TIG",
        "TIG vs stick",
        "skill level",
        "material type",
        "material thickness",
        "process comparison"
      ]
    }
  },
  {
    "id": "image:quick_start_overview",
    "type": "image",
    "label": "6-step quick start visual poster for first-time setup",
    "meta": {
      "topic": "quick_start_overview",
      "images": [
        "qsg_p01_setup_steps.png"
      ],
      "keywords": [
        "quick start",
        "first time setup",
        "getting started",
        "6 steps",
        "beginner setup"
      ]
    }
  },
  {
    "id": "image:spool_gun_setup",
    "type": "image",
    "label": "Optional Spool Gun setup: Ground Clamp in Negative, Wire Feed Power in Positive,",
    "meta": {
      "topic": "spool_gun_setup",
      "images": [
        "owner_p17_tension_test_nozzle_spool_gun.png"
      ],
      "keywords": [
        "spool gun",
        "aluminum welding",
        "optional spool gun"
      ]
    }
  },
  {
    "id": "image:overheating_warning",
    "type": "image",
    "label": "LCD warning screen showing problem/remedy for Duty Cycle Exceeded, Low Voltage I",
    "meta": {
      "topic": "overheating_warning",
      "images": [
        "owner_p23_post_welding_overheating.png"
      ],
      "keywords": [
        "overheating",
        "warning screen",
        "thermal shutdown",
        "duty cycle exceeded",
        "low voltage",
        "high voltage"
      ]
    }
  }
];

export const edges: GraphEdge[] = [
  {
    "source": "process:mig",
    "target": "polarity:dcep",
    "type": "uses_polarity",
    "label": "MIG uses DCEP"
  },
  {
    "source": "process:flux_cored",
    "target": "polarity:dcen",
    "type": "uses_polarity",
    "label": "Flux-Cored uses DCEN"
  },
  {
    "source": "process:tig",
    "target": "polarity:dcen",
    "type": "uses_polarity",
    "label": "TIG uses DCEN"
  },
  {
    "source": "process:stick",
    "target": "polarity:dcep",
    "type": "uses_polarity",
    "label": "Stick uses DCEP"
  },
  {
    "source": "process:mig",
    "target": "voltage:120vac",
    "type": "supports_voltage",
    "label": "MIG on 120VAC",
    "meta": {
      "current_range": [
        30,
        140
      ]
    }
  },
  {
    "source": "process:mig",
    "target": "voltage:240vac",
    "type": "supports_voltage",
    "label": "MIG on 240VAC",
    "meta": {
      "current_range": [
        30,
        220
      ]
    }
  },
  {
    "source": "process:tig",
    "target": "voltage:120vac",
    "type": "supports_voltage",
    "label": "TIG on 120VAC",
    "meta": {
      "current_range": [
        10,
        125
      ]
    }
  },
  {
    "source": "process:tig",
    "target": "voltage:240vac",
    "type": "supports_voltage",
    "label": "TIG on 240VAC",
    "meta": {
      "current_range": [
        10,
        175
      ]
    }
  },
  {
    "source": "process:stick",
    "target": "voltage:120vac",
    "type": "supports_voltage",
    "label": "Stick on 120VAC",
    "meta": {
      "current_range": [
        10,
        80
      ]
    }
  },
  {
    "source": "process:stick",
    "target": "voltage:240vac",
    "type": "supports_voltage",
    "label": "Stick on 240VAC",
    "meta": {
      "current_range": [
        10,
        175
      ]
    }
  },
  {
    "source": "process:mig",
    "target": "material:mild_steel",
    "type": "welds_material",
    "label": "MIG welds Mild Steel"
  },
  {
    "source": "process:mig",
    "target": "material:stainless_steel",
    "type": "welds_material",
    "label": "MIG welds Stainless Steel"
  },
  {
    "source": "process:mig",
    "target": "material:aluminum_with_optional_spool_gun",
    "type": "welds_material",
    "label": "MIG welds Aluminum (with optional Spool Gun)"
  },
  {
    "source": "process:tig",
    "target": "material:mild_steel",
    "type": "welds_material",
    "label": "TIG welds Mild Steel"
  },
  {
    "source": "process:tig",
    "target": "material:stainless_steel",
    "type": "welds_material",
    "label": "TIG welds Stainless Steel"
  },
  {
    "source": "process:tig",
    "target": "material:chrome_moly",
    "type": "welds_material",
    "label": "TIG welds Chrome Moly"
  },
  {
    "source": "process:stick",
    "target": "material:mild_steel",
    "type": "welds_material",
    "label": "Stick welds Mild Steel"
  },
  {
    "source": "process:stick",
    "target": "material:stainless_steel",
    "type": "welds_material",
    "label": "Stick welds Stainless Steel"
  },
  {
    "source": "process:flux_cored",
    "target": "material:steel",
    "type": "welds_material",
    "label": "Flux-Cored welds Steel"
  },
  {
    "source": "process:flux_cored",
    "target": "material:stainless_steel",
    "type": "welds_material",
    "label": "Flux-Cored welds Stainless Steel"
  },
  {
    "source": "process:mig",
    "target": "gas:c25",
    "type": "requires_gas",
    "label": "MIG uses C25 for mild steel"
  },
  {
    "source": "process:mig",
    "target": "gas:stainless_tri_mix",
    "type": "requires_gas",
    "label": "MIG uses Tri-Mix for stainless"
  },
  {
    "source": "process:mig",
    "target": "gas:100pct_argon",
    "type": "requires_gas",
    "label": "MIG uses Argon for aluminum"
  },
  {
    "source": "process:flux_cored",
    "target": "gas:none",
    "type": "requires_gas",
    "label": "Flux-Cored: no gas needed"
  },
  {
    "source": "process:tig",
    "target": "gas:100pct_argon",
    "type": "requires_gas",
    "label": "TIG uses 100% Argon"
  },
  {
    "source": "process:stick",
    "target": "gas:none",
    "type": "requires_gas",
    "label": "Stick: no gas needed"
  },
  {
    "source": "process:mig",
    "target": "duty_cycle:mig_120vac_100a",
    "type": "has_duty_cycle",
    "label": "40% at 100A on 120VAC"
  },
  {
    "source": "process:mig",
    "target": "duty_cycle:mig_120vac_75a",
    "type": "has_duty_cycle",
    "label": "100% at 75A on 120VAC"
  },
  {
    "source": "process:mig",
    "target": "duty_cycle:mig_240vac_200a",
    "type": "has_duty_cycle",
    "label": "25% at 200A on 240VAC"
  },
  {
    "source": "process:mig",
    "target": "duty_cycle:mig_240vac_115a",
    "type": "has_duty_cycle",
    "label": "100% at 115A on 240VAC"
  },
  {
    "source": "process:tig",
    "target": "duty_cycle:tig_120vac_125a",
    "type": "has_duty_cycle",
    "label": "40% at 125A on 120VAC"
  },
  {
    "source": "process:tig",
    "target": "duty_cycle:tig_120vac_90a",
    "type": "has_duty_cycle",
    "label": "100% at 90A on 120VAC"
  },
  {
    "source": "process:tig",
    "target": "duty_cycle:tig_240vac_175a",
    "type": "has_duty_cycle",
    "label": "30% at 175A on 240VAC"
  },
  {
    "source": "process:tig",
    "target": "duty_cycle:tig_240vac_105a",
    "type": "has_duty_cycle",
    "label": "100% at 105A on 240VAC"
  },
  {
    "source": "process:stick",
    "target": "duty_cycle:stick_120vac_80a",
    "type": "has_duty_cycle",
    "label": "40% at 80A on 120VAC"
  },
  {
    "source": "process:stick",
    "target": "duty_cycle:stick_120vac_60a",
    "type": "has_duty_cycle",
    "label": "100% at 60A on 120VAC"
  },
  {
    "source": "process:stick",
    "target": "duty_cycle:stick_240vac_175a",
    "type": "has_duty_cycle",
    "label": "25% at 175A on 240VAC"
  },
  {
    "source": "process:stick",
    "target": "duty_cycle:stick_240vac_100a",
    "type": "has_duty_cycle",
    "label": "100% at 100A on 240VAC"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_spatter",
    "type": "has_problem",
    "label": "MIG: spatter"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_spatter",
    "type": "has_problem",
    "label": "Flux-Cored: spatter"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_poor_penetration",
    "type": "has_problem",
    "label": "MIG: poor_penetration"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_poor_penetration",
    "type": "has_problem",
    "label": "Flux-Cored: poor_penetration"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_burn_through",
    "type": "has_problem",
    "label": "MIG: burn_through"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_burn_through",
    "type": "has_problem",
    "label": "Flux-Cored: burn_through"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_good_weld",
    "type": "has_problem",
    "label": "Good Weld"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_good_weld",
    "type": "has_problem",
    "label": "Good Weld"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_voltage_too_low_or_wire_feed_too_slow",
    "type": "has_problem",
    "label": "Voltage Too Low or Wire Feed Too Slow"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_voltage_too_low_or_wire_feed_too_slow",
    "type": "has_problem",
    "label": "Voltage Too Low or Wire Feed Too Slow"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_voltage_too_high_or_wire_feed_too_fast",
    "type": "has_problem",
    "label": "Voltage Too High or Wire Feed Too Fast"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_voltage_too_high_or_wire_feed_too_fast",
    "type": "has_problem",
    "label": "Voltage Too High or Wire Feed Too Fast"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_travel_speed_too_fast",
    "type": "has_problem",
    "label": "Travel Speed Too Fast"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_travel_speed_too_fast",
    "type": "has_problem",
    "label": "Travel Speed Too Fast"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_travel_speed_too_slow",
    "type": "has_problem",
    "label": "Travel Speed Too Slow"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_travel_speed_too_slow",
    "type": "has_problem",
    "label": "Travel Speed Too Slow"
  },
  {
    "source": "process:mig",
    "target": "defect:wire_example_ctwd_too_long_or_wrong_polarity",
    "type": "has_problem",
    "label": "CTWD Too Long or Wrong Polarity"
  },
  {
    "source": "process:flux_cored",
    "target": "defect:wire_example_ctwd_too_long_or_wrong_polarity",
    "type": "has_problem",
    "label": "CTWD Too Long or Wrong Polarity"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_slag",
    "type": "has_problem",
    "label": "Stick: slag"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_undercut",
    "type": "has_problem",
    "label": "Stick: undercut"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_poor_penetration",
    "type": "has_problem",
    "label": "Stick: poor_penetration"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_burn_through",
    "type": "has_problem",
    "label": "Stick: burn_through"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_good_weld",
    "type": "has_problem",
    "label": "Good Weld"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_current_too_low",
    "type": "has_problem",
    "label": "Current Too Low"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_current_too_high",
    "type": "has_problem",
    "label": "Current Too High"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_weld_speed_too_fast",
    "type": "has_problem",
    "label": "Weld Speed Too Fast"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_weld_speed_too_slow",
    "type": "has_problem",
    "label": "Weld Speed Too Slow"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_arc_length_too_short",
    "type": "has_problem",
    "label": "Arc Length Too Short"
  },
  {
    "source": "process:stick",
    "target": "defect:stick_example_arc_length_too_long",
    "type": "has_problem",
    "label": "Arc Length Too Long"
  },
  {
    "source": "defect:wire_poor_penetration",
    "target": "defect:stick_poor_penetration",
    "type": "related_to",
    "label": "Same defect across processes"
  },
  {
    "source": "defect:wire_burn_through",
    "target": "defect:stick_burn_through",
    "type": "related_to",
    "label": "Same defect across processes"
  },
  {
    "source": "process:mig",
    "target": "problem:wire_feed_motor_runs_but_wire_does_not_feed_proper",
    "type": "has_problem",
    "label": "MIG: Wire Feed Motor Runs but Wire Does Not F"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:wire_feed_motor_runs_but_wire_does_not_feed_proper",
    "type": "has_problem",
    "label": "Flux-Cored: Wire Feed Motor Runs but Wire Does Not F"
  },
  {
    "source": "process:mig",
    "target": "problem:wire_creates_a_bird_s_nest_during_operation",
    "type": "has_problem",
    "label": "MIG: Wire Creates a Bird's Nest During Operat"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:wire_creates_a_bird_s_nest_during_operation",
    "type": "has_problem",
    "label": "Flux-Cored: Wire Creates a Bird's Nest During Operat"
  },
  {
    "source": "process:mig",
    "target": "problem:wire_stops_during_welding",
    "type": "has_problem",
    "label": "MIG: Wire Stops During Welding"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:wire_stops_during_welding",
    "type": "has_problem",
    "label": "Flux-Cored: Wire Stops During Welding"
  },
  {
    "source": "process:mig",
    "target": "problem:welding_arc_not_stable",
    "type": "has_problem",
    "label": "MIG: Welding Arc Not Stable"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:welding_arc_not_stable",
    "type": "has_problem",
    "label": "Flux-Cored: Welding Arc Not Stable"
  },
  {
    "source": "polarity:dcep",
    "target": "problem:welding_arc_not_stable",
    "type": "related_to",
    "label": "Polarity-related"
  },
  {
    "source": "polarity:dcen",
    "target": "problem:welding_arc_not_stable",
    "type": "related_to",
    "label": "Polarity-related"
  },
  {
    "source": "process:mig",
    "target": "problem:weak_arc_strength",
    "type": "has_problem",
    "label": "MIG: Weak Arc Strength"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:weak_arc_strength",
    "type": "has_problem",
    "label": "Flux-Cored: Weak Arc Strength"
  },
  {
    "source": "process:mig",
    "target": "problem:welder_does_not_function_when_switched_on",
    "type": "has_problem",
    "label": "MIG: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:welder_does_not_function_when_switched_on",
    "type": "has_problem",
    "label": "Flux-Cored: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:tig",
    "target": "problem:welder_does_not_function_when_switched_on",
    "type": "has_problem",
    "label": "TIG: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:stick",
    "target": "problem:welder_does_not_function_when_switched_on",
    "type": "has_problem",
    "label": "Stick: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:mig",
    "target": "problem:lcd_display_does_not_light_when_welder_is_switched",
    "type": "has_problem",
    "label": "MIG: LCD Display Does Not Light When Welder i"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:lcd_display_does_not_light_when_welder_is_switched",
    "type": "has_problem",
    "label": "Flux-Cored: LCD Display Does Not Light When Welder i"
  },
  {
    "source": "process:tig",
    "target": "problem:lcd_display_does_not_light_when_welder_is_switched",
    "type": "has_problem",
    "label": "TIG: LCD Display Does Not Light When Welder i"
  },
  {
    "source": "process:stick",
    "target": "problem:lcd_display_does_not_light_when_welder_is_switched",
    "type": "has_problem",
    "label": "Stick: LCD Display Does Not Light When Welder i"
  },
  {
    "source": "process:mig",
    "target": "problem:wire_feeds_but_arc_does_not_ignite",
    "type": "has_problem",
    "label": "MIG: Wire Feeds, but Arc Does Not Ignite"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:wire_feeds_but_arc_does_not_ignite",
    "type": "has_problem",
    "label": "Flux-Cored: Wire Feeds, but Arc Does Not Ignite"
  },
  {
    "source": "process:mig",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "has_problem",
    "label": "MIG: Porosity in the Weld Metal"
  },
  {
    "source": "process:flux_cored",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "has_problem",
    "label": "Flux-Cored: Porosity in the Weld Metal"
  },
  {
    "source": "polarity:dcep",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "related_to",
    "label": "Polarity-related"
  },
  {
    "source": "polarity:dcen",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "related_to",
    "label": "Polarity-related"
  },
  {
    "source": "process:tig",
    "target": "problem:welder_does_not_function_when_switched_on_tig_stic",
    "type": "has_problem",
    "label": "TIG: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:stick",
    "target": "problem:welder_does_not_function_when_switched_on_tig_stic",
    "type": "has_problem",
    "label": "Stick: Welder Does Not Function When Switched O"
  },
  {
    "source": "process:tig",
    "target": "problem:weak_arc_strength_tig_stick",
    "type": "has_problem",
    "label": "TIG: Weak Arc Strength (TIG/Stick)"
  },
  {
    "source": "process:stick",
    "target": "problem:weak_arc_strength_tig_stick",
    "type": "has_problem",
    "label": "Stick: Weak Arc Strength (TIG/Stick)"
  },
  {
    "source": "process:tig",
    "target": "problem:welding_arc_not_stable_tig_stick",
    "type": "has_problem",
    "label": "TIG: Welding Arc Not Stable (TIG/Stick)"
  },
  {
    "source": "process:stick",
    "target": "problem:welding_arc_not_stable_tig_stick",
    "type": "has_problem",
    "label": "Stick: Welding Arc Not Stable (TIG/Stick)"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_wire_spool_installation",
    "type": "has_setup_phase",
    "label": "Wire Spool Installation"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_feed_roller_setup",
    "type": "has_setup_phase",
    "label": "Feed Roller Setup"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_gun_cable_connection",
    "type": "has_setup_phase",
    "label": "Gun Cable Connection"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_wire_feed_control_cable",
    "type": "has_setup_phase",
    "label": "Wire Feed Control Cable"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_polarity_setup_dcep_for_mig",
    "type": "has_setup_phase",
    "label": "Polarity Setup — DCEP for MIG"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_gas_setup",
    "type": "has_setup_phase",
    "label": "Gas Setup"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_wire_threading",
    "type": "has_setup_phase",
    "label": "Wire Threading"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_power_up_and_wire_feed",
    "type": "has_setup_phase",
    "label": "Power Up and Wire Feed"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_drive_tension_test",
    "type": "has_setup_phase",
    "label": "Drive Tension Test"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_final_assembly",
    "type": "has_setup_phase",
    "label": "Final Assembly"
  },
  {
    "source": "process:mig",
    "target": "setup:mig_lcd_settings",
    "type": "has_setup_phase",
    "label": "LCD Settings"
  },
  {
    "source": "process:flux_cored",
    "target": "setup:flux_cored_differences",
    "type": "has_setup_phase",
    "label": "Differences from MIG setup"
  },
  {
    "source": "process:flux_cored",
    "target": "process:mig",
    "type": "related_to",
    "label": "Shares setup steps with MIG (except polarity and gas)"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_connect_cables",
    "type": "has_setup_phase",
    "label": "Connect Cables"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_connect_shielding_gas",
    "type": "has_setup_phase",
    "label": "Connect Shielding Gas"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_connect_power_cord",
    "type": "has_setup_phase",
    "label": "Connect Power Cord"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_sharpen_tungsten_electrode",
    "type": "has_setup_phase",
    "label": "Sharpen Tungsten Electrode"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_assemble_tig_torch",
    "type": "has_setup_phase",
    "label": "Assemble TIG Torch"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_lcd_settings",
    "type": "has_setup_phase",
    "label": "LCD Settings"
  },
  {
    "source": "process:tig",
    "target": "setup:tig_welding_technique",
    "type": "has_setup_phase",
    "label": "Welding Technique"
  },
  {
    "source": "process:stick",
    "target": "setup:stick_connect_cables",
    "type": "has_setup_phase",
    "label": "Connect Cables"
  },
  {
    "source": "process:stick",
    "target": "setup:stick_connect_power_cord",
    "type": "has_setup_phase",
    "label": "Connect Power Cord"
  },
  {
    "source": "process:stick",
    "target": "setup:stick_lcd_settings",
    "type": "has_setup_phase",
    "label": "LCD Settings"
  },
  {
    "source": "process:stick",
    "target": "setup:stick_welding_technique",
    "type": "has_setup_phase",
    "label": "Welding Technique"
  },
  {
    "source": "process:mig",
    "target": "image:front_panel_layout",
    "type": "depicted_in",
    "label": "Front panel controls"
  },
  {
    "source": "process:flux_cored",
    "target": "image:front_panel_layout",
    "type": "depicted_in",
    "label": "Front panel controls"
  },
  {
    "source": "process:tig",
    "target": "image:front_panel_layout",
    "type": "depicted_in",
    "label": "Front panel controls"
  },
  {
    "source": "process:stick",
    "target": "image:front_panel_layout",
    "type": "depicted_in",
    "label": "Front panel controls"
  },
  {
    "source": "process:mig",
    "target": "image:polarity_mig_dcep",
    "type": "depicted_in",
    "label": "MIG: polarity_mig_dcep"
  },
  {
    "source": "polarity:dcep",
    "target": "image:polarity_mig_dcep",
    "type": "depicted_in",
    "label": "DCEP diagram"
  },
  {
    "source": "process:flux_cored",
    "target": "image:polarity_flux_dcen",
    "type": "depicted_in",
    "label": "Flux-Cored: polarity_flux_dcen"
  },
  {
    "source": "polarity:dcen",
    "target": "image:polarity_flux_dcen",
    "type": "depicted_in",
    "label": "DCEN diagram"
  },
  {
    "source": "process:tig",
    "target": "image:polarity_tig",
    "type": "depicted_in",
    "label": "TIG: polarity_tig"
  },
  {
    "source": "polarity:dcen",
    "target": "image:polarity_tig",
    "type": "depicted_in",
    "label": "DCEN diagram"
  },
  {
    "source": "process:stick",
    "target": "image:polarity_stick",
    "type": "depicted_in",
    "label": "Stick: polarity_stick"
  },
  {
    "source": "polarity:dcep",
    "target": "image:polarity_stick",
    "type": "depicted_in",
    "label": "DCEP (Stick) diagram"
  },
  {
    "source": "polarity:dcep",
    "target": "image:polarity_all_processes",
    "type": "depicted_in",
    "label": "DCEP diagram"
  },
  {
    "source": "polarity:dcen",
    "target": "image:polarity_all_processes",
    "type": "depicted_in",
    "label": "DCEN diagram"
  },
  {
    "source": "process:mig",
    "target": "image:wire_spool_installation",
    "type": "depicted_in",
    "label": "MIG: wire_spool_installation"
  },
  {
    "source": "process:flux_cored",
    "target": "image:wire_spool_installation",
    "type": "depicted_in",
    "label": "Flux-Cored: wire_spool_installation"
  },
  {
    "source": "process:mig",
    "target": "image:wire_threading_and_tension",
    "type": "depicted_in",
    "label": "MIG: wire_threading_and_tension"
  },
  {
    "source": "process:flux_cored",
    "target": "image:wire_threading_and_tension",
    "type": "depicted_in",
    "label": "Flux-Cored: wire_threading_and_tension"
  },
  {
    "source": "process:mig",
    "target": "image:duty_cycle_mig",
    "type": "depicted_in",
    "label": "MIG: duty_cycle_mig"
  },
  {
    "source": "duty_cycle:mig_120vac_100a",
    "target": "image:duty_cycle_mig",
    "type": "depicted_in",
    "label": "MIG duty cycle chart"
  },
  {
    "source": "duty_cycle:mig_120vac_75a",
    "target": "image:duty_cycle_mig",
    "type": "depicted_in",
    "label": "MIG duty cycle chart"
  },
  {
    "source": "duty_cycle:mig_240vac_200a",
    "target": "image:duty_cycle_mig",
    "type": "depicted_in",
    "label": "MIG duty cycle chart"
  },
  {
    "source": "duty_cycle:mig_240vac_115a",
    "target": "image:duty_cycle_mig",
    "type": "depicted_in",
    "label": "MIG duty cycle chart"
  },
  {
    "source": "process:tig",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "TIG: duty_cycle_tig_stick"
  },
  {
    "source": "process:stick",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "Stick: duty_cycle_tig_stick"
  },
  {
    "source": "duty_cycle:tig_120vac_125a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "TIG duty cycle chart"
  },
  {
    "source": "duty_cycle:tig_120vac_90a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "TIG duty cycle chart"
  },
  {
    "source": "duty_cycle:tig_240vac_175a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "TIG duty cycle chart"
  },
  {
    "source": "duty_cycle:tig_240vac_105a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "TIG duty cycle chart"
  },
  {
    "source": "duty_cycle:stick_120vac_80a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "Stick duty cycle chart"
  },
  {
    "source": "duty_cycle:stick_120vac_60a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "Stick duty cycle chart"
  },
  {
    "source": "duty_cycle:stick_240vac_175a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "Stick duty cycle chart"
  },
  {
    "source": "duty_cycle:stick_240vac_100a",
    "target": "image:duty_cycle_tig_stick",
    "type": "depicted_in",
    "label": "Stick duty cycle chart"
  },
  {
    "source": "process:mig",
    "target": "image:settings_mig",
    "type": "depicted_in",
    "label": "MIG: settings_mig"
  },
  {
    "source": "process:flux_cored",
    "target": "image:settings_mig",
    "type": "depicted_in",
    "label": "Flux-Cored LCD settings"
  },
  {
    "source": "process:tig",
    "target": "image:settings_tig",
    "type": "depicted_in",
    "label": "TIG: settings_tig"
  },
  {
    "source": "process:stick",
    "target": "image:settings_stick",
    "type": "depicted_in",
    "label": "Stick: settings_stick"
  },
  {
    "source": "process:mig",
    "target": "image:welding_technique_wire",
    "type": "depicted_in",
    "label": "MIG: welding_technique_wire"
  },
  {
    "source": "process:flux_cored",
    "target": "image:welding_technique_wire",
    "type": "depicted_in",
    "label": "Flux-Cored: welding_technique_wire"
  },
  {
    "source": "process:tig",
    "target": "image:electrode_grinding_torch_assembly",
    "type": "depicted_in",
    "label": "TIG: electrode_grinding_torch_assembly"
  },
  {
    "source": "process:mig",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "MIG: weld_diagnosis_wire"
  },
  {
    "source": "process:flux_cored",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Flux-Cored: weld_diagnosis_wire"
  },
  {
    "source": "process:stick",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Stick: weld_diagnosis_stick"
  },
  {
    "source": "process:mig",
    "target": "image:selection_chart",
    "type": "depicted_in",
    "label": "Process selection chart"
  },
  {
    "source": "process:flux_cored",
    "target": "image:selection_chart",
    "type": "depicted_in",
    "label": "Process selection chart"
  },
  {
    "source": "process:tig",
    "target": "image:selection_chart",
    "type": "depicted_in",
    "label": "Process selection chart"
  },
  {
    "source": "process:stick",
    "target": "image:selection_chart",
    "type": "depicted_in",
    "label": "Process selection chart"
  },
  {
    "source": "problem:wire_feed_motor_runs_but_wire_does_not_feed_proper",
    "target": "defect:wire_spatter",
    "type": "related_to",
    "label": "Wire feed issues cause spatter"
  },
  {
    "source": "problem:welding_arc_not_stable",
    "target": "defect:wire_spatter",
    "type": "related_to",
    "label": "Unstable arc causes spatter"
  },
  {
    "source": "problem:wire_feeds_but_arc_does_not_ignite",
    "target": "defect:wire_spatter",
    "type": "related_to",
    "label": "Wire feed issues cause spatter"
  },
  {
    "source": "problem:porosity_in_the_weld_metal",
    "target": "gas:c25",
    "type": "related_to",
    "label": "Gas supply affects porosity"
  },
  {
    "source": "problem:porosity_in_the_weld_metal",
    "target": "gas:none",
    "type": "related_to",
    "label": "No gas causes porosity in MIG"
  },
  {
    "source": "problem:welding_arc_not_stable_tig_stick",
    "target": "defect:wire_spatter",
    "type": "related_to",
    "label": "Unstable arc causes spatter"
  },
  {
    "source": "defect:wire_spatter",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:wire_poor_penetration",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:wire_burn_through",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:stick_slag",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:stick_undercut",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:stick_poor_penetration",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:stick_burn_through",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Shown in diagnosis chart"
  },
  {
    "source": "defect:wire_example_good_weld",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:wire_example_voltage_too_low_or_wire_feed_too_slow",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:wire_example_voltage_too_high_or_wire_feed_too_fast",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:wire_example_travel_speed_too_fast",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:wire_example_travel_speed_too_slow",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:wire_example_ctwd_too_long_or_wrong_polarity",
    "target": "image:weld_diagnosis_wire",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_good_weld",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_current_too_low",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_current_too_high",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_weld_speed_too_fast",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_weld_speed_too_slow",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_arc_length_too_short",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "defect:stick_example_arc_length_too_long",
    "target": "image:weld_diagnosis_stick",
    "type": "depicted_in",
    "label": "Example weld photo"
  },
  {
    "source": "setup:mig_wire_spool_installation",
    "target": "image:wire_spool_installation",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_feed_roller_setup",
    "target": "image:feed_roller_selection",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_gun_cable_connection",
    "target": "image:gun_cable_connector",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_wire_threading",
    "target": "image:wire_threading_and_tension",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_gas_setup",
    "target": "image:gas_cylinder_setup",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_polarity_setup_dcep_for_mig",
    "target": "image:polarity_mig_dcep",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:mig_lcd_settings",
    "target": "image:settings_mig",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:tig_connect_shielding_gas",
    "target": "image:gas_cylinder_setup",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:tig_sharpen_tungsten_electrode",
    "target": "image:electrode_grinding_torch_assembly",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:tig_assemble_tig_torch",
    "target": "image:electrode_grinding_torch_assembly",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:tig_lcd_settings",
    "target": "image:settings_tig",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:tig_connect_cables",
    "target": "image:polarity_tig",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:stick_connect_cables",
    "target": "image:polarity_stick",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "setup:stick_lcd_settings",
    "target": "image:settings_stick",
    "type": "depicted_in",
    "label": "Setup illustrated in diagram"
  },
  {
    "source": "duty_cycle:mig_120vac_100a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "MIG duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:mig_120vac_75a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "MIG duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:mig_240vac_200a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "MIG duty cycle on 240VAC"
  },
  {
    "source": "duty_cycle:mig_240vac_115a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "MIG duty cycle on 240VAC"
  },
  {
    "source": "duty_cycle:tig_120vac_125a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "TIG duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:tig_120vac_90a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "TIG duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:tig_240vac_175a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "TIG duty cycle on 240VAC"
  },
  {
    "source": "duty_cycle:tig_240vac_105a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "TIG duty cycle on 240VAC"
  },
  {
    "source": "duty_cycle:stick_120vac_80a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "Stick duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:stick_120vac_60a",
    "target": "voltage:120vac",
    "type": "applies_to",
    "label": "Stick duty cycle on 120VAC"
  },
  {
    "source": "duty_cycle:stick_240vac_175a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "Stick duty cycle on 240VAC"
  },
  {
    "source": "duty_cycle:stick_240vac_100a",
    "target": "voltage:240vac",
    "type": "applies_to",
    "label": "Stick duty cycle on 240VAC"
  },
  {
    "source": "gas:c25",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "causes",
    "label": "Empty/wrong gas"
  },
  {
    "source": "process:mig",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "causes",
    "label": "Dirty workpiece"
  },
  {
    "source": "polarity:dcep",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "causes",
    "label": "Incorrect polarity"
  },
  {
    "source": "polarity:dcen",
    "target": "problem:porosity_in_the_weld_metal",
    "type": "causes",
    "label": "Incorrect polarity"
  }
];
